// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System.Collections.Generic;

namespace BarisCemant.Verimor.WhatsApp
{
    internal static class RawOperations
    {
        public static readonly RawOperation HealthHealthGet =
            new RawOperation(
                "health_health_get",
                "GET",
                "/health",
                new Dictionary<string, string> { },
                null);

        public static readonly RawOperation SendOtpV1MessagesOtpPost =
            new RawOperation(
                "send_otp_v1_messages_otp_post",
                "POST",
                "/v1/messages/otp",
                new Dictionary<string, string> { ["x-api-key"] = "header" },
                null);

        public static readonly RawOperation SendUtilityV1MessagesUtilityPost =
            new RawOperation(
                "send_utility_v1_messages_utility_post",
                "POST",
                "/v1/messages/utility",
                new Dictionary<string, string> { ["x-api-key"] = "header" },
                null);

        public static readonly IReadOnlyList<RawOperation> All = new RawOperation[]
        {
            HealthHealthGet,
            SendOtpV1MessagesOtpPost,
            SendUtilityV1MessagesUtilityPost,
        };
    }
}
