// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using BarisCemant.Verimor.Http;

namespace BarisCemant.Verimor.WhatsApp
{
    public sealed partial class WhatsAppClient
    {
        public WhatsAppClient(WhatsAppClientOptions options)
        {
            if (options == null) throw new ArgumentNullException(nameof(options));
            var core = new ProductCore(
                new VerimorTransport(options, new Uri("https://wapi.verimor.com.tr/")),
                options.ToCredentials(),
                null);
            Raw = new RawClient(core, RawOperations.All);
            Health = new HealthService(core);
            Messages = new MessagesService(core);
        }

        public RawClient Raw { get; }

        public HealthService Health { get; }

        public MessagesService Messages { get; }
    }
}
