// GET /v1/messages/{message_ref} — Mesaj Kaydını Sorgula
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.WhatsApp;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.WhatsApp
{
    public static class GetMessageExample
    {
        public static async Task RunAsync()
        {
            var client = new WhatsAppClient(new WhatsAppClientOptions
            {
                ApiKey = Environment.GetEnvironmentVariable("VERIMOR_WHATSAPP_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://wapi.verimor.com.tr"),
            });
            var result = await client.Messages.GetMessageAsync(
                messageRef: "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            );
            Console.WriteLine(result);
        }
    }
}
