// GET /v1/messages — Mesajları Listele / Ara
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.WhatsApp;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.WhatsApp
{
    public static class ListMessagesExample
    {
        public static async Task RunAsync()
        {
            var client = new WhatsAppClient(new WhatsAppClientOptions
            {
                ApiKey = Environment.GetEnvironmentVariable("VERIMOR_WHATSAPP_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://wapi.verimor.com.tr"),
            });
            var result = await client.Messages.ListMessagesAsync();
            Console.WriteLine(result);
        }
    }
}
