// POST /v1/messages/otp — OTP / Kimlik Doğrulama Mesajı Gönder
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.WhatsApp;
using BarisCemant.Verimor.WhatsApp.Generated.Model;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.WhatsApp
{
    public static class SendOtpExample
    {
        public static async Task RunAsync()
        {
            var client = new WhatsAppClient(new WhatsAppClientOptions
            {
                ApiKey = Environment.GetEnvironmentVariable("VERIMOR_WHATSAPP_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://wapi.verimor.com.tr"),
            });
            var result = await client.Messages.SendOtpAsync(
                request: new TemplateMessageRequest(
                    to: "905001112233",
                    templateName: "siparis_onay")
            );
            Console.WriteLine(result);
        }
    }
}
