// POST /v1/messages/bulk — Toplu Şablon Mesajı Gönder
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.WhatsApp;
using BarisCemant.Verimor.WhatsApp.Generated.Model;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Examples.Operations.WhatsApp
{
    public static class SendBulkExample
    {
        public static async Task RunAsync()
        {
            var client = new WhatsAppClient(new WhatsAppClientOptions
            {
                ApiKey = Environment.GetEnvironmentVariable("VERIMOR_WHATSAPP_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://wapi.verimor.com.tr"),
            });
            var result = await client.Messages.SendBulkAsync(
                request: new BulkMessageRequest(
                    templateName: "odeme_hatirlatici",
                    recipients: new List<BulkRecipient>
                    {
                        new BulkRecipient(
                            to: "905001112233"),
                    })
            );
            Console.WriteLine(result);
        }
    }
}
