// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System.Collections.Generic;

namespace BarisCemant.Verimor.Switch
{
    internal static class RawOperations
    {
        public static readonly RawOperation AnswerCall =
            new RawOperation(
                "answerCall",
                "GET",
                "/answer/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation AnswerCallPost =
            new RawOperation(
                "answerCallPost",
                "POST",
                "/answer",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateAnnouncement =
            new RawOperation(
                "createAnnouncement",
                "POST",
                "/announcements",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateBlockedNumber =
            new RawOperation(
                "createBlockedNumber",
                "POST",
                "/blocked_numbers",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateBridge =
            new RawOperation(
                "createBridge",
                "GET",
                "/bridge",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateContact =
            new RawOperation(
                "createContact",
                "POST",
                "/contacts",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateContactGroup =
            new RawOperation(
                "createContactGroup",
                "POST",
                "/contact_groups",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateDnd =
            new RawOperation(
                "createDnd",
                "GET",
                "/dnd/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateFaxDocumentUrl =
            new RawOperation(
                "createFaxDocumentUrl",
                "POST",
                "/fax_document_url",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateFaxOrder =
            new RawOperation(
                "createFaxOrder",
                "POST",
                "/fax_orders",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateIvrCampaign =
            new RawOperation(
                "createIvrCampaign",
                "POST",
                "/ivr_campaigns.json",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateRecordingUrl =
            new RawOperation(
                "createRecordingUrl",
                "POST",
                "/recording_url",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateVoicemailRecordingUrl =
            new RawOperation(
                "createVoicemailRecordingUrl",
                "POST",
                "/voicemail_recording_url",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation CreateWebphoneToken =
            new RawOperation(
                "createWebphoneToken",
                "POST",
                "/webphone_tokens",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation DeleteAnnouncement =
            new RawOperation(
                "deleteAnnouncement",
                "DELETE",
                "/announcements/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation DeleteBlockedNumber =
            new RawOperation(
                "deleteBlockedNumber",
                "DELETE",
                "/blocked_numbers/delete",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation DeleteContact =
            new RawOperation(
                "deleteContact",
                "DELETE",
                "/contacts/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation DeleteContactGroup =
            new RawOperation(
                "deleteContactGroup",
                "DELETE",
                "/contact_groups/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation DeleteIvrCampaign =
            new RawOperation(
                "deleteIvrCampaign",
                "DELETE",
                "/ivr_campaigns/{id}.json",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation DownloadFaxDocument =
            new RawOperation(
                "downloadFaxDocument",
                "GET",
                "/fax_document/{id}",
                new Dictionary<string, string> { },
                null);

        public static readonly RawOperation GetAnnouncements =
            new RawOperation(
                "getAnnouncements",
                "GET",
                "/announcements",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation GetCallerIds =
            new RawOperation(
                "getCallerIds",
                "GET",
                "/caller_ids",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation GetCdr =
            new RawOperation(
                "getCdr",
                "GET",
                "/cdrs/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation GetCdrs =
            new RawOperation(
                "getCdrs",
                "GET",
                "/cdrs",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation GetCrmIntegrations =
            new RawOperation(
                "getCrmIntegrations",
                "GET",
                "/crm_integrations",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation GetExtension =
            new RawOperation(
                "getExtension",
                "GET",
                "/extensions/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation GetQueueUserList =
            new RawOperation(
                "getQueueUserList",
                "GET",
                "/queue/user_list",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation GetQueues =
            new RawOperation(
                "getQueues",
                "GET",
                "/queues",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation GetQueuesPending =
            new RawOperation(
                "getQueuesPending",
                "GET",
                "/queues/pending",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation GetVoicemailMessages =
            new RawOperation(
                "getVoicemailMessages",
                "GET",
                "/voicemail_messages",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation HangupCall =
            new RawOperation(
                "hangupCall",
                "GET",
                "/hangup/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation ListAgentStatuses =
            new RawOperation(
                "listAgentStatuses",
                "GET",
                "/agent_statuses",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation ListBlockedNumbers =
            new RawOperation(
                "listBlockedNumbers",
                "GET",
                "/blocked_numbers",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation ListContactGroups =
            new RawOperation(
                "listContactGroups",
                "GET",
                "/contact_groups",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation ListContacts =
            new RawOperation(
                "listContacts",
                "GET",
                "/contacts",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation ListExtensions =
            new RawOperation(
                "listExtensions",
                "GET",
                "/extensions",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation ListFaxOrders =
            new RawOperation(
                "listFaxOrders",
                "GET",
                "/fax_orders",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation ListFdrs =
            new RawOperation(
                "listFdrs",
                "GET",
                "/fdrs",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation ListUserStatuses =
            new RawOperation(
                "listUserStatuses",
                "GET",
                "/user_statuses",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation ManageQueueUsers =
            new RawOperation(
                "manageQueueUsers",
                "GET",
                "/queue/manage_users",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation MuteCall =
            new RawOperation(
                "muteCall",
                "GET",
                "/mute/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation OriginateCall =
            new RawOperation(
                "originateCall",
                "GET",
                "/originate",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation OriginateCallPost =
            new RawOperation(
                "originateCallPost",
                "POST",
                "/originate",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation TransferCall =
            new RawOperation(
                "transferCall",
                "GET",
                "/transfer/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation TransferCallPost =
            new RawOperation(
                "transferCallPost",
                "POST",
                "/transfer",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation UpdateAnnouncement =
            new RawOperation(
                "updateAnnouncement",
                "PATCH",
                "/announcements/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation UpdateContact =
            new RawOperation(
                "updateContact",
                "PATCH",
                "/contacts/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation UpdateContactGroup =
            new RawOperation(
                "updateContactGroup",
                "PATCH",
                "/contact_groups/{id}",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation UpdateCrmIntegrations =
            new RawOperation(
                "updateCrmIntegrations",
                "POST",
                "/crm_integrations",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation UpdateIvrCampaign =
            new RawOperation(
                "updateIvrCampaign",
                "PATCH",
                "/ivr_campaigns/{id}.json",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation UpdateOutboundCallerId =
            new RawOperation(
                "updateOutboundCallerId",
                "GET",
                "/update_outbound_caller_id",
                new Dictionary<string, string> { ["key"] = "query" },
                null);

        public static readonly RawOperation WebhookPayloadExamples =
            new RawOperation(
                "webhookPayloadExamples",
                "GET",
                "/webhook-payload-examples",
                new Dictionary<string, string> { },
                null);

        public static readonly IReadOnlyList<RawOperation> All = new RawOperation[]
        {
            AnswerCall,
            AnswerCallPost,
            CreateAnnouncement,
            CreateBlockedNumber,
            CreateBridge,
            CreateContact,
            CreateContactGroup,
            CreateDnd,
            CreateFaxDocumentUrl,
            CreateFaxOrder,
            CreateIvrCampaign,
            CreateRecordingUrl,
            CreateVoicemailRecordingUrl,
            CreateWebphoneToken,
            DeleteAnnouncement,
            DeleteBlockedNumber,
            DeleteContact,
            DeleteContactGroup,
            DeleteIvrCampaign,
            DownloadFaxDocument,
            GetAnnouncements,
            GetCallerIds,
            GetCdr,
            GetCdrs,
            GetCrmIntegrations,
            GetExtension,
            GetQueueUserList,
            GetQueues,
            GetQueuesPending,
            GetVoicemailMessages,
            HangupCall,
            ListAgentStatuses,
            ListBlockedNumbers,
            ListContactGroups,
            ListContacts,
            ListExtensions,
            ListFaxOrders,
            ListFdrs,
            ListUserStatuses,
            ManageQueueUsers,
            MuteCall,
            OriginateCall,
            OriginateCallPost,
            TransferCall,
            TransferCallPost,
            UpdateAnnouncement,
            UpdateContact,
            UpdateContactGroup,
            UpdateCrmIntegrations,
            UpdateIvrCampaign,
            UpdateOutboundCallerId,
            WebhookPayloadExamples,
        };
    }
}
