// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using BarisCemant.Verimor.Http;

namespace BarisCemant.Verimor.Switch
{
    public sealed partial class SwitchClient
    {
        public SwitchClient(SwitchClientOptions options)
        {
            if (options == null) throw new ArgumentNullException(nameof(options));
            var core = new ProductCore(
                new VerimorTransport(options, new Uri("https://api.bulutsantralim.com/")),
                options.ToCredentials(),
                null);
            Raw = new RawClient(core, RawOperations.All);
            Announcements = new AnnouncementsService(core);
            Blacklist = new BlacklistService(core);
            CallerIds = new CallerIdsService(core);
            Calls = new CallsService(core);
            Contacts = new ContactsService(core);
            Crm = new CrmService(core);
            Fax = new FaxService(core);
            IvrCampaigns = new IvrCampaignsService(core);
            Queues = new QueuesService(core);
            Records = new RecordsService(core);
            Users = new UsersService(core);
        }

        public RawClient Raw { get; }

        public AnnouncementsService Announcements { get; }

        public BlacklistService Blacklist { get; }

        public CallerIdsService CallerIds { get; }

        public CallsService Calls { get; }

        public ContactsService Contacts { get; }

        public CrmService Crm { get; }

        public FaxService Fax { get; }

        public IvrCampaignsService IvrCampaigns { get; }

        public QueuesService Queues { get; }

        public RecordsService Records { get; }

        public UsersService Users { get; }
    }
}
