// POST /v2/cancel/{id} — Gönderim İptali
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Sms;
using BarisCemant.Verimor.Sms.Generated.Model;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Sms
{
    public static class CancelExample
    {
        public static async Task RunAsync()
        {
            var client = new SmsClient(new SmsClientOptions
            {
                Username = Environment.GetEnvironmentVariable("VERIMOR_SMS_USERNAME") ?? string.Empty,
                Password = Environment.GetEnvironmentVariable("VERIMOR_SMS_PASSWORD") ?? string.Empty,
                DefaultSender = Environment.GetEnvironmentVariable("VERIMOR_SMS_SENDER") ?? "VERIMOR",
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://sms.verimor.com.tr"),
            });
            var result = await client.Campaigns.CancelAsync(
                id: "123",
                request: new PostV2CancelIdRequest(
                    username: "",
                    password: "")
            );
            Console.WriteLine(result);
        }
    }
}
