// DELETE /v2/blacklists/{id} — Kara Listeden Silme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Sms;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Sms
{
    public static class DeleteBlacklistEntryExample
    {
        public static async Task RunAsync()
        {
            var client = new SmsClient(new SmsClientOptions
            {
                Username = Environment.GetEnvironmentVariable("VERIMOR_SMS_USERNAME") ?? string.Empty,
                Password = Environment.GetEnvironmentVariable("VERIMOR_SMS_PASSWORD") ?? string.Empty,
                DefaultSender = Environment.GetEnvironmentVariable("VERIMOR_SMS_SENDER") ?? "VERIMOR",
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://sms.verimor.com.tr"),
            });
            var result = await client.Blacklist.DeleteBlacklistEntryAsync(
                id: "123"
            );
            Console.WriteLine(result);
        }
    }
}
