// POST /v2/send.json — SMS Gönderme (JSON)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Sms;
using BarisCemant.Verimor.Sms.Generated.Model;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Examples.Operations.Sms
{
    public static class SendExample
    {
        public static async Task RunAsync()
        {
            var client = new SmsClient(new SmsClientOptions
            {
                Username = Environment.GetEnvironmentVariable("VERIMOR_SMS_USERNAME") ?? string.Empty,
                Password = Environment.GetEnvironmentVariable("VERIMOR_SMS_PASSWORD") ?? string.Empty,
                DefaultSender = Environment.GetEnvironmentVariable("VERIMOR_SMS_SENDER") ?? "VERIMOR",
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://sms.verimor.com.tr"),
            });
            var result = await client.Campaigns.SendAsync(
                request: new SendSmsJsonRequest(
                    username: "",
                    password: "",
                    messages: new List<SendSmsJsonRequestMessagesInner>
                    {
                        new SendSmsJsonRequestMessagesInner(
                            dest: "905111111111,905111111112",
                            msg: "Deneme Mesaj"),
                    })
            );
            Console.WriteLine(result);
        }
    }
}
