// POST /v2/otp — OTP Gönderme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Sms;
using BarisCemant.Verimor.Sms.Generated.Model;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Sms
{
    public static class SendOtpExample
    {
        public static async Task RunAsync()
        {
            var client = new SmsClient(new SmsClientOptions
            {
                Username = Environment.GetEnvironmentVariable("VERIMOR_SMS_USERNAME") ?? string.Empty,
                Password = Environment.GetEnvironmentVariable("VERIMOR_SMS_PASSWORD") ?? string.Empty,
                DefaultSender = Environment.GetEnvironmentVariable("VERIMOR_SMS_SENDER") ?? "VERIMOR",
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://sms.verimor.com.tr"),
            });
            var result = await client.Campaigns.SendOtpAsync(
                request: new OtpRequest(
                    username: "",
                    password: "",
                    dest: "905001234567",
                    code: "482931")
            );
            Console.WriteLine(result);
        }
    }
}
