// POST /v2/iys_consents.json — İzin Yönetimi
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Sms;
using BarisCemant.Verimor.Sms.Generated.Model;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading.Tasks;

namespace Examples.Operations.Sms
{
    public static class SubmitIysConsentsExample
    {
        public static async Task RunAsync()
        {
            var client = new SmsClient(new SmsClientOptions
            {
                Username = Environment.GetEnvironmentVariable("VERIMOR_SMS_USERNAME") ?? string.Empty,
                Password = Environment.GetEnvironmentVariable("VERIMOR_SMS_PASSWORD") ?? string.Empty,
                DefaultSender = Environment.GetEnvironmentVariable("VERIMOR_SMS_SENDER") ?? "VERIMOR",
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://sms.verimor.com.tr"),
            });
            var result = await client.Iys.SubmitIysConsentsAsync(
                request: new PostV2IysConsentsJsonRequest(
                    username: "",
                    password: "",
                    sourceAddr: Environment.GetEnvironmentVariable("VERIMOR_SMS_SENDER") ?? "VERIMOR",
                    consents: new List<PostV2IysConsentsJsonRequestConsentsInner>
                    {
                        new PostV2IysConsentsJsonRequestConsentsInner(
                            type: "MESAJ",
                            source: "HS_WEB",
                            status: "ONAY",
                            recipientType: "BIREYSEL",
                            consentDate: DateTimeOffset.Parse("2022-04-14 13:30:30", CultureInfo.InvariantCulture),
                            recipient: "905001112233"),
                    })
            );
            Console.WriteLine(result);
        }
    }
}
