// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class AnnouncementsService
    {
        private readonly ProductCore _core;

        internal AnnouncementsService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /announcements</summary>
        public async Task<string> CreateAnnouncementAsync(
            string name,
            string sounddata,
            CancellationToken cancellationToken = default)
        {
            if (name == null) throw new ArgumentNullException(nameof(name));
            if (sounddata == null) throw new ArgumentNullException(nameof(sounddata));
            var verimorCall = new CallParts();
            verimorCall.AddForm("name", name);
            verimorCall.AddForm("sounddata", sounddata);
            var verimorReply = await _core.SendAsync(RawOperations.CreateAnnouncement, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>DELETE /announcements/{id}</summary>
        public async Task<string> DeleteAnnouncementAsync(
            string id,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.DeleteAnnouncement, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /announcements</summary>
        public async Task<IReadOnlyList<GetAnnouncements200ResponseInner>> ListAnnouncementsAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.GetAnnouncements, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<GetAnnouncements200ResponseInner>>(verimorReply);
        }

        /// <summary>PATCH /announcements/{id}</summary>
        public async Task<string> UpdateAnnouncementAsync(
            string id,
            string? name = null,
            string? sounddata = null,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            verimorCall.AddForm("name", name);
            verimorCall.AddForm("sounddata", sounddata);
            var verimorReply = await _core.SendAsync(RawOperations.UpdateAnnouncement, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
