// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class BlacklistService
    {
        private readonly ProductCore _core;

        internal BlacklistService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /blocked_numbers</summary>
        public async Task<string> CreateBlockedNumberAsync(
            string number,
            string? direction = null,
            CancellationToken cancellationToken = default)
        {
            if (number == null) throw new ArgumentNullException(nameof(number));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("number", number);
            verimorCall.AddQuery("direction", direction);
            var verimorReply = await _core.SendAsync(RawOperations.CreateBlockedNumber, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>DELETE /blocked_numbers/delete</summary>
        public async Task<string> DeleteBlockedNumberAsync(
            string number,
            string? direction = null,
            CancellationToken cancellationToken = default)
        {
            if (number == null) throw new ArgumentNullException(nameof(number));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("number", number);
            verimorCall.AddQuery("direction", direction);
            var verimorReply = await _core.SendAsync(RawOperations.DeleteBlockedNumber, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /blocked_numbers</summary>
        public async Task<ListBlockedNumbers200Response> ListBlockedNumbersAsync(
            long? page = null,
            long? limit = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("page", page);
            verimorCall.AddQuery("limit", limit);
            var verimorReply = await _core.SendAsync(RawOperations.ListBlockedNumbers, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<ListBlockedNumbers200Response>(verimorReply);
        }
    }
}
