// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class CallsService
    {
        private readonly ProductCore _core;

        internal CallsService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /answer</summary>
        public async Task<string> AnswerAsync(
            AnswerCallPostRequest request,
            CancellationToken cancellationToken = default)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            var verimorCall = new CallParts();
            verimorCall.JsonBody = VerimorJson.Serialize(request);
            var verimorReply = await _core.SendAsync(RawOperations.AnswerCallPost, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /answer/{id}</summary>
        public async Task<string> AnswerLegacyAsync(
            string id,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.AnswerCall, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /bridge</summary>
        public async Task<string> BridgeAsync(
            string source,
            string destination,
            string? callerId = null,
            long? timeout = null,
            long? announcementToCaller = null,
            long? announcementToCallee = null,
            bool? recordingEnabled = null,
            CancellationToken cancellationToken = default)
        {
            if (source == null) throw new ArgumentNullException(nameof(source));
            if (destination == null) throw new ArgumentNullException(nameof(destination));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("source", source);
            verimorCall.AddQuery("destination", destination);
            verimorCall.AddQuery("caller_id", callerId);
            verimorCall.AddQuery("timeout", timeout);
            verimorCall.AddQuery("announcement_to_caller", announcementToCaller);
            verimorCall.AddQuery("announcement_to_callee", announcementToCallee);
            verimorCall.AddQuery("recording_enabled", recordingEnabled);
            var verimorReply = await _core.SendAsync(RawOperations.CreateBridge, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /hangup/{id}</summary>
        public async Task<string> HangupAsync(
            string id,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.HangupCall, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>POST /originate</summary>
        public async Task<string> OriginateAsync(
            OriginateCallPostRequest request,
            CancellationToken cancellationToken = default)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            var verimorCall = new CallParts();
            verimorCall.JsonBody = VerimorJson.Serialize(request);
            var verimorReply = await _core.SendAsync(RawOperations.OriginateCallPost, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /originate</summary>
        public async Task<string> OriginateLegacyAsync(
            string extension,
            string destination,
            string? callerId = null,
            bool? manualAnswer = null,
            long? timeout = null,
            long? announcementToCallee = null,
            long? announcementToCaller = null,
            string? customCallType = null,
            CancellationToken cancellationToken = default)
        {
            if (extension == null) throw new ArgumentNullException(nameof(extension));
            if (destination == null) throw new ArgumentNullException(nameof(destination));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("extension", extension);
            verimorCall.AddQuery("destination", destination);
            verimorCall.AddQuery("caller_id", callerId);
            verimorCall.AddQuery("manual_answer", manualAnswer);
            verimorCall.AddQuery("timeout", timeout);
            verimorCall.AddQuery("announcement_to_callee", announcementToCallee);
            verimorCall.AddQuery("announcement_to_caller", announcementToCaller);
            verimorCall.AddQuery("custom_call_type", customCallType);
            var verimorReply = await _core.SendAsync(RawOperations.OriginateCall, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /mute/{id}</summary>
        public async Task<string> SetCallMuteAsync(
            string id,
            string state,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            if (state == null) throw new ArgumentNullException(nameof(state));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            verimorCall.AddQuery("state", state);
            var verimorReply = await _core.SendAsync(RawOperations.MuteCall, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>POST /transfer</summary>
        public async Task<string> TransferAsync(
            string id,
            string userNumber,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            if (userNumber == null) throw new ArgumentNullException(nameof(userNumber));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("id", id);
            verimorCall.AddQuery("user_number", userNumber);
            var verimorReply = await _core.SendAsync(RawOperations.TransferCallPost, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /transfer/{id}</summary>
        public async Task<string> TransferLegacyAsync(
            string id,
            string userNumber,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            if (userNumber == null) throw new ArgumentNullException(nameof(userNumber));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            verimorCall.AddQuery("user_number", userNumber);
            var verimorReply = await _core.SendAsync(RawOperations.TransferCall, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
