// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class CallerIdsService
    {
        private readonly ProductCore _core;

        internal CallerIdsService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>GET /caller_ids</summary>
        public async Task<IReadOnlyList<string>> ListCallerIdsAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.GetCallerIds, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<string>>(verimorReply);
        }

        /// <summary>GET /update_outbound_caller_id</summary>
        public async Task<string> UpdateOutboundCallerIdAsync(
            string extension,
            string callerId,
            CancellationToken cancellationToken = default)
        {
            if (extension == null) throw new ArgumentNullException(nameof(extension));
            if (callerId == null) throw new ArgumentNullException(nameof(callerId));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("extension", extension);
            verimorCall.AddQuery("caller_id", callerId);
            var verimorReply = await _core.SendAsync(RawOperations.UpdateOutboundCallerId, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
