// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class ContactsService
    {
        private readonly ProductCore _core;

        internal ContactsService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /contacts</summary>
        public async Task<string> CreateContactAsync(
            string name,
            string surname,
            string phone,
            string? salutation = null,
            string? tckn = null,
            string? description = null,
            string? phone1 = null,
            string? email = null,
            string? title = null,
            string? phone2 = null,
            string? fax = null,
            string? gender = null,
            string? birthday = null,
            bool? birthdaySms = null,
            string? weddingday = null,
            bool? weddingdaySms = null,
            string? address = null,
            string? note1 = null,
            string? note2 = null,
            string? note3 = null,
            string? note4 = null,
            string? companyName = null,
            long? monthlySmsDay = null,
            string? monthlySmsMessage = null,
            IEnumerable<long>? groupIds = null,
            CancellationToken cancellationToken = default)
        {
            if (name == null) throw new ArgumentNullException(nameof(name));
            if (surname == null) throw new ArgumentNullException(nameof(surname));
            if (phone == null) throw new ArgumentNullException(nameof(phone));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("name", name);
            verimorCall.AddQuery("surname", surname);
            verimorCall.AddQuery("phone", phone);
            verimorCall.AddQuery("salutation", salutation);
            verimorCall.AddQuery("tckn", tckn);
            verimorCall.AddQuery("description", description);
            verimorCall.AddQuery("phone1", phone1);
            verimorCall.AddQuery("email", email);
            verimorCall.AddQuery("title", title);
            verimorCall.AddQuery("phone2", phone2);
            verimorCall.AddQuery("fax", fax);
            verimorCall.AddQuery("gender", gender);
            verimorCall.AddQuery("birthday", birthday);
            verimorCall.AddQuery("birthday_sms", birthdaySms);
            verimorCall.AddQuery("weddingday", weddingday);
            verimorCall.AddQuery("weddingday_sms", weddingdaySms);
            verimorCall.AddQuery("address", address);
            verimorCall.AddQuery("note1", note1);
            verimorCall.AddQuery("note2", note2);
            verimorCall.AddQuery("note3", note3);
            verimorCall.AddQuery("note4", note4);
            verimorCall.AddQuery("company_name", companyName);
            verimorCall.AddQuery("monthly_sms_day", monthlySmsDay);
            verimorCall.AddQuery("monthly_sms_message", monthlySmsMessage);
            verimorCall.AddQuery("group_ids", groupIds);
            var verimorReply = await _core.SendAsync(RawOperations.CreateContact, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>POST /contact_groups</summary>
        public async Task<string> CreateContactGroupAsync(
            string name,
            CancellationToken cancellationToken = default)
        {
            if (name == null) throw new ArgumentNullException(nameof(name));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("name", name);
            var verimorReply = await _core.SendAsync(RawOperations.CreateContactGroup, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>DELETE /contacts/{id}</summary>
        public async Task<string> DeleteContactAsync(
            long id,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.DeleteContact, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>DELETE /contact_groups/{id}</summary>
        public async Task<string> DeleteContactGroupAsync(
            long id,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.DeleteContactGroup, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /contact_groups</summary>
        public async Task<IReadOnlyList<ListContactGroups200ResponseInner>> ListContactGroupsAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.ListContactGroups, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<ListContactGroups200ResponseInner>>(verimorReply);
        }

        /// <summary>GET /contacts</summary>
        public async Task<ListContacts200Response> ListContactsAsync(
            long? page = null,
            long? limit = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("page", page);
            verimorCall.AddQuery("limit", limit);
            var verimorReply = await _core.SendAsync(RawOperations.ListContacts, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<ListContacts200Response>(verimorReply);
        }

        /// <summary>PATCH /contacts/{id}</summary>
        public async Task<string> UpdateContactAsync(
            long id,
            string? salutation = null,
            string? name = null,
            string? surname = null,
            string? tckn = null,
            string? description = null,
            string? phone = null,
            string? phone1 = null,
            string? email = null,
            string? title = null,
            string? phone2 = null,
            string? fax = null,
            string? gender = null,
            string? birthday = null,
            bool? birthdaySms = null,
            string? weddingday = null,
            bool? weddingdaySms = null,
            string? address = null,
            string? note1 = null,
            string? note2 = null,
            string? note3 = null,
            string? note4 = null,
            string? companyName = null,
            long? monthlySmsDay = null,
            string? monthlySmsMessage = null,
            IEnumerable<long>? groupIds = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            verimorCall.AddQuery("salutation", salutation);
            verimorCall.AddQuery("name", name);
            verimorCall.AddQuery("surname", surname);
            verimorCall.AddQuery("tckn", tckn);
            verimorCall.AddQuery("description", description);
            verimorCall.AddQuery("phone", phone);
            verimorCall.AddQuery("phone1", phone1);
            verimorCall.AddQuery("email", email);
            verimorCall.AddQuery("title", title);
            verimorCall.AddQuery("phone2", phone2);
            verimorCall.AddQuery("fax", fax);
            verimorCall.AddQuery("gender", gender);
            verimorCall.AddQuery("birthday", birthday);
            verimorCall.AddQuery("birthday_sms", birthdaySms);
            verimorCall.AddQuery("weddingday", weddingday);
            verimorCall.AddQuery("weddingday_sms", weddingdaySms);
            verimorCall.AddQuery("address", address);
            verimorCall.AddQuery("note1", note1);
            verimorCall.AddQuery("note2", note2);
            verimorCall.AddQuery("note3", note3);
            verimorCall.AddQuery("note4", note4);
            verimorCall.AddQuery("company_name", companyName);
            verimorCall.AddQuery("monthly_sms_day", monthlySmsDay);
            verimorCall.AddQuery("monthly_sms_message", monthlySmsMessage);
            verimorCall.AddQuery("group_ids", groupIds);
            var verimorReply = await _core.SendAsync(RawOperations.UpdateContact, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>PATCH /contact_groups/{id}</summary>
        public async Task<string> UpdateContactGroupAsync(
            long id,
            string name,
            CancellationToken cancellationToken = default)
        {
            if (name == null) throw new ArgumentNullException(nameof(name));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            verimorCall.AddQuery("name", name);
            var verimorReply = await _core.SendAsync(RawOperations.UpdateContactGroup, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
