// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class CrmService
    {
        private readonly ProductCore _core;

        internal CrmService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>GET /crm_integrations</summary>
        public async Task<GetCrmIntegrations200Response> GetCrmIntegrationsAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.GetCrmIntegrations, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<GetCrmIntegrations200Response>(verimorReply);
        }

        /// <summary>GET /webhook-payload-examples</summary>
        public async Task<WebhookPayloadExamples200Response> GetWebhookPayloadExamplesAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.WebhookPayloadExamples, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<WebhookPayloadExamples200Response>(verimorReply);
        }

        /// <summary>POST /crm_integrations</summary>
        public async Task<string> UpdateCrmIntegrationsAsync(
            string? ringing = null,
            string? answered = null,
            string? hangup = null,
            string? notificationUrl = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("ringing", ringing);
            verimorCall.AddQuery("answered", answered);
            verimorCall.AddQuery("hangup", hangup);
            verimorCall.AddQuery("notification_url", notificationUrl);
            var verimorReply = await _core.SendAsync(RawOperations.UpdateCrmIntegrations, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
