// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class FaxService
    {
        private readonly ProductCore _core;

        internal FaxService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /fax_document_url</summary>
        public async Task<string> CreateFaxDocumentUrlAsync(
            string callUuid,
            CancellationToken cancellationToken = default)
        {
            if (callUuid == null) throw new ArgumentNullException(nameof(callUuid));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("call_uuid", callUuid);
            var verimorReply = await _core.SendAsync(RawOperations.CreateFaxDocumentUrl, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>POST /fax_orders</summary>
        public async Task<string> CreateFaxOrderAsync(
            string remoteStationId,
            string filedata,
            string? localStationId = null,
            string? localStationHeader = null,
            CancellationToken cancellationToken = default)
        {
            if (remoteStationId == null) throw new ArgumentNullException(nameof(remoteStationId));
            if (filedata == null) throw new ArgumentNullException(nameof(filedata));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("remote_station_id", remoteStationId);
            verimorCall.AddQuery("filedata", filedata);
            verimorCall.AddQuery("local_station_id", localStationId);
            verimorCall.AddQuery("local_station_header", localStationHeader);
            var verimorReply = await _core.SendAsync(RawOperations.CreateFaxOrder, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /fax_document/{id}</summary>
        public async Task<byte[]> DownloadFaxDocumentAsync(
            string id,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.DownloadFaxDocument, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Bytes(verimorReply);
        }

        /// <summary>GET /fax_orders</summary>
        public async Task<ListFaxOrders200Response> ListFaxOrdersAsync(
            long? page = null,
            long? limit = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("page", page);
            verimorCall.AddQuery("limit", limit);
            var verimorReply = await _core.SendAsync(RawOperations.ListFaxOrders, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<ListFaxOrders200Response>(verimorReply);
        }

        /// <summary>GET /fdrs</summary>
        public async Task<ListFdrs200Response> ListFaxRecordsAsync(
            string? startStampFrom = null,
            string? startStampTo = null,
            string? direction = null,
            string? callerIdNumber = null,
            string? originalDestination = null,
            string? success = null,
            long? page = null,
            long? limit = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("start_stamp_from", startStampFrom);
            verimorCall.AddQuery("start_stamp_to", startStampTo);
            verimorCall.AddQuery("direction", direction);
            verimorCall.AddQuery("caller_id_number", callerIdNumber);
            verimorCall.AddQuery("original_destination", originalDestination);
            verimorCall.AddQuery("success", success);
            verimorCall.AddQuery("page", page);
            verimorCall.AddQuery("limit", limit);
            var verimorReply = await _core.SendAsync(RawOperations.ListFdrs, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<ListFdrs200Response>(verimorReply);
        }
    }
}
