// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class IvrCampaignsService
    {
        private readonly ProductCore _core;

        internal IvrCampaignsService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /ivr_campaigns.json</summary>
        public async Task<string> CreateIvrCampaignAsync(
            CreateIvrCampaignRequest request,
            CancellationToken cancellationToken = default)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            var verimorCall = new CallParts();
            verimorCall.JsonBody = VerimorJson.Serialize(request);
            var verimorReply = await _core.SendAsync(RawOperations.CreateIvrCampaign, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>DELETE /ivr_campaigns/{id}.json</summary>
        public async Task<string> DeleteIvrCampaignAsync(
            string id,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.DeleteIvrCampaign, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>PATCH /ivr_campaigns/{id}.json</summary>
        public async Task<string> UpdateIvrCampaignAsync(
            string id,
            string status,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            if (status == null) throw new ArgumentNullException(nameof(status));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            verimorCall.AddQuery("status", status);
            var verimorReply = await _core.SendAsync(RawOperations.UpdateIvrCampaign, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
