// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class QueuesService
    {
        private readonly ProductCore _core;

        internal QueuesService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>GET /queues/pending</summary>
        public async Task<IReadOnlyList<GetQueuesPending200ResponseInner>> ListQueuePendingCallsAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.GetQueuesPending, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<GetQueuesPending200ResponseInner>>(verimorReply);
        }

        /// <summary>GET /queue/user_list</summary>
        public async Task<IReadOnlyList<GetQueueUserList200ResponseInner>> ListQueueUsersAsync(
            string queueNumber,
            CancellationToken cancellationToken = default)
        {
            if (queueNumber == null) throw new ArgumentNullException(nameof(queueNumber));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("queue_number", queueNumber);
            var verimorReply = await _core.SendAsync(RawOperations.GetQueueUserList, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<GetQueueUserList200ResponseInner>>(verimorReply);
        }

        /// <summary>GET /queues</summary>
        public async Task<IReadOnlyList<GetQueues200ResponseInner>> ListQueuesAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.GetQueues, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<GetQueues200ResponseInner>>(verimorReply);
        }

        /// <summary>GET /queue/manage_users</summary>
        public async Task<string> ManageQueueUsersAsync(
            string queueNumber,
            string userList,
            CancellationToken cancellationToken = default)
        {
            if (queueNumber == null) throw new ArgumentNullException(nameof(queueNumber));
            if (userList == null) throw new ArgumentNullException(nameof(userList));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("queue_number", queueNumber);
            verimorCall.AddQuery("user_list", userList);
            var verimorReply = await _core.SendAsync(RawOperations.ManageQueueUsers, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
