// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class RecordsService
    {
        private readonly ProductCore _core;

        internal RecordsService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /recording_url</summary>
        public async Task<string> CreateRecordingUrlAsync(
            string callUuid,
            CancellationToken cancellationToken = default)
        {
            if (callUuid == null) throw new ArgumentNullException(nameof(callUuid));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("call_uuid", callUuid);
            var verimorReply = await _core.SendAsync(RawOperations.CreateRecordingUrl, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>POST /voicemail_recording_url</summary>
        public async Task<string> CreateVoicemailRecordingUrlAsync(
            string uuid,
            CancellationToken cancellationToken = default)
        {
            if (uuid == null) throw new ArgumentNullException(nameof(uuid));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("uuid", uuid);
            var verimorReply = await _core.SendAsync(RawOperations.CreateVoicemailRecordingUrl, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /cdrs/{id}</summary>
        public async Task<GetCdr200Response> GetCdrAsync(
            string id,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.GetCdr, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<GetCdr200Response>(verimorReply);
        }

        /// <summary>GET /cdrs</summary>
        public async Task<GetCdrs200Response> ListCdrsAsync(
            string? startStampFrom = null,
            string? startStampTo = null,
            string? recordingPresent = null,
            string? direction = null,
            string? callerIdNumber = null,
            string? destinationNumber = null,
            string? missed = null,
            string? queue = null,
            long? page = null,
            long? limit = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("start_stamp_from", startStampFrom);
            verimorCall.AddQuery("start_stamp_to", startStampTo);
            verimorCall.AddQuery("recording_present", recordingPresent);
            verimorCall.AddQuery("direction", direction);
            verimorCall.AddQuery("caller_id_number", callerIdNumber);
            verimorCall.AddQuery("destination_number", destinationNumber);
            verimorCall.AddQuery("missed", missed);
            verimorCall.AddQuery("queue", queue);
            verimorCall.AddQuery("page", page);
            verimorCall.AddQuery("limit", limit);
            var verimorReply = await _core.SendAsync(RawOperations.GetCdrs, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<GetCdrs200Response>(verimorReply);
        }

        /// <summary>GET /voicemail_messages</summary>
        public async Task<GetVoicemailMessages200Response> ListVoicemailMessagesAsync(
            string? startStampFrom = null,
            string? startStampTo = null,
            string? read = null,
            string? userNumber = null,
            string? uuid = null,
            long? page = null,
            long? limit = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("start_stamp_from", startStampFrom);
            verimorCall.AddQuery("start_stamp_to", startStampTo);
            verimorCall.AddQuery("read", read);
            verimorCall.AddQuery("user_number", userNumber);
            verimorCall.AddQuery("uuid", uuid);
            verimorCall.AddQuery("page", page);
            verimorCall.AddQuery("limit", limit);
            var verimorReply = await _core.SendAsync(RawOperations.GetVoicemailMessages, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<GetVoicemailMessages200Response>(verimorReply);
        }
    }
}
