// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Switch.Generated.Model;

namespace BarisCemant.Verimor.Switch
{
    public sealed class UsersService
    {
        private readonly ProductCore _core;

        internal UsersService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /webphone_tokens</summary>
        public async Task<string> CreateWebphoneTokenAsync(
            string extension,
            CancellationToken cancellationToken = default)
        {
            if (extension == null) throw new ArgumentNullException(nameof(extension));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("extension", extension);
            var verimorReply = await _core.SendAsync(RawOperations.CreateWebphoneToken, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /extensions/{id}</summary>
        public async Task<GetExtension200Response> GetExtensionAsync(
            string id,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.GetExtension, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<GetExtension200Response>(verimorReply);
        }

        /// <summary>GET /agent_statuses</summary>
        public async Task<IReadOnlyList<ListAgentStatuses200ResponseInner>> ListAgentStatusesAsync(
            string? agent = null,
            string? queue = null,
            string? status = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("agent", agent);
            verimorCall.AddQuery("queue", queue);
            verimorCall.AddQuery("status", status);
            var verimorReply = await _core.SendAsync(RawOperations.ListAgentStatuses, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<ListAgentStatuses200ResponseInner>>(verimorReply);
        }

        /// <summary>GET /extensions</summary>
        public async Task<IReadOnlyList<ListExtensions200ResponseInner>> ListExtensionsAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.ListExtensions, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<ListExtensions200ResponseInner>>(verimorReply);
        }

        /// <summary>GET /user_statuses</summary>
        public async Task<IReadOnlyList<ListUserStatuses200ResponseInner>> ListUserStatusesAsync(
            string? user = null,
            string? status = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("user", user);
            verimorCall.AddQuery("status", status);
            var verimorReply = await _core.SendAsync(RawOperations.ListUserStatuses, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<ListUserStatuses200ResponseInner>>(verimorReply);
        }

        /// <summary>GET /dnd/{id}</summary>
        public async Task<string> SetDndAsync(
            string id,
            string state,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            if (state == null) throw new ArgumentNullException(nameof(state));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            verimorCall.AddQuery("state", state);
            var verimorReply = await _core.SendAsync(RawOperations.CreateDnd, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
