// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Sms.Generated.Model;

namespace BarisCemant.Verimor.Sms
{
    public sealed class BalancesService
    {
        private readonly ProductCore _core;

        internal BalancesService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>GET /v2/balance</summary>
        public async Task<string> BalanceAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.GetV2Balance, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
