// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Sms.Generated.Model;

namespace BarisCemant.Verimor.Sms
{
    public sealed class BlacklistService
    {
        private readonly ProductCore _core;

        internal BlacklistService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /v2/blacklists</summary>
        public async Task<string> AddBlacklistEntryAsync(
            string phones,
            CancellationToken cancellationToken = default)
        {
            if (phones == null) throw new ArgumentNullException(nameof(phones));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("phones", phones);
            var verimorReply = await _core.SendAsync(RawOperations.PostV2Blacklists, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>DELETE /v2/blacklists/{id}</summary>
        public async Task<string> DeleteBlacklistEntryAsync(
            string id,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            var verimorReply = await _core.SendAsync(RawOperations.DeleteV2BlacklistsId, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /v2/blacklists</summary>
        public async Task<GetV2Blacklists200Response> ListBlacklistEntriesAsync(
            long? offset = null,
            long? limit = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("offset", offset);
            verimorCall.AddQuery("limit", limit);
            var verimorReply = await _core.SendAsync(RawOperations.GetV2Blacklists, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<GetV2Blacklists200Response>(verimorReply);
        }
    }
}
