// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Sms.Generated.Model;

namespace BarisCemant.Verimor.Sms
{
    public sealed class CampaignsService
    {
        private readonly ProductCore _core;

        internal CampaignsService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /v2/cancel/{id}</summary>
        public async Task<string> CancelAsync(
            string id,
            PostV2CancelIdRequest request,
            CancellationToken cancellationToken = default)
        {
            if (id == null) throw new ArgumentNullException(nameof(id));
            if (request == null) throw new ArgumentNullException(nameof(request));
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            verimorCall.JsonBody = VerimorJson.Serialize(request);
            var verimorReply = await _core.SendAsync(RawOperations.PostV2CancelId, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>POST /v2/send.json</summary>
        public async Task<string> SendAsync(
            SendSmsJsonRequest request,
            CancellationToken cancellationToken = default)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            var verimorCall = new CallParts();
            verimorCall.JsonBody = VerimorJson.Serialize(request);
            var verimorReply = await _core.SendAsync(RawOperations.SendSmsJson, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }

        /// <summary>GET /v2/send</summary>
        public async Task<string> SendLegacyAsync(
            string dest,
            string msg,
            string? sourceAddr = null,
            string? validFor = null,
            long? datacoding = null,
            bool? isCommercial = null,
            string? iysRecipientType = null,
            string? sendAt = null,
            CancellationToken cancellationToken = default)
        {
            if (dest == null) throw new ArgumentNullException(nameof(dest));
            if (msg == null) throw new ArgumentNullException(nameof(msg));
            var verimorCall = new CallParts();
            verimorCall.AddQuery("dest", dest);
            verimorCall.AddQuery("msg", msg);
            verimorCall.AddQuery("source_addr", sourceAddr);
            verimorCall.AddQuery("valid_for", validFor);
            verimorCall.AddQuery("datacoding", datacoding);
            verimorCall.AddQuery("is_commercial", isCommercial);
            verimorCall.AddQuery("iys_recipient_type", iysRecipientType);
            verimorCall.AddQuery("send_at", sendAt);
            var verimorReply = await _core.SendAsync(RawOperations.GetV2Send, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
