// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Sms.Generated.Model;

namespace BarisCemant.Verimor.Sms
{
    public sealed class IysService
    {
        private readonly ProductCore _core;

        internal IysService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>GET /v2/iys/campaigns/{id}/consents</summary>
        public async Task<GetV2IysCampaignsIdConsents200Response> ListIysCampaignConsentsAsync(
            long id,
            long? offset = null,
            long? limit = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddPath("id", id);
            verimorCall.AddQuery("offset", offset);
            verimorCall.AddQuery("limit", limit);
            var verimorReply = await _core.SendAsync(RawOperations.GetV2IysCampaignsIdConsents, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<GetV2IysCampaignsIdConsents200Response>(verimorReply);
        }

        /// <summary>GET /v2/iys/campaigns</summary>
        public async Task<GetV2IysCampaigns200Response> ListIysCampaignsAsync(
            long? offset = null,
            long? limit = null,
            string? source = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("offset", offset);
            verimorCall.AddQuery("limit", limit);
            verimorCall.AddQuery("source", source);
            var verimorReply = await _core.SendAsync(RawOperations.GetV2IysCampaigns, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<GetV2IysCampaigns200Response>(verimorReply);
        }

        /// <summary>POST /v2/iys_consents.json</summary>
        public async Task<string> SubmitIysConsentsAsync(
            PostV2IysConsentsJsonRequest request,
            CancellationToken cancellationToken = default)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            var verimorCall = new CallParts();
            verimorCall.JsonBody = VerimorJson.Serialize(request);
            var verimorReply = await _core.SendAsync(RawOperations.PostV2IysConsentsJson, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Text(verimorReply);
        }
    }
}
