// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Sms.Generated.Model;

namespace BarisCemant.Verimor.Sms
{
    public sealed class ReportsService
    {
        private readonly ProductCore _core;

        internal ReportsService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>GET /v2/inbound_messages</summary>
        public async Task<IReadOnlyList<GetV2InboundMessages200ResponseInner>> ListInboundMessagesAsync(
            string? fromTime = null,
            string? toTime = null,
            long? greaterThan = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("from_time", fromTime);
            verimorCall.AddQuery("to_time", toTime);
            verimorCall.AddQuery("greater_than", greaterThan);
            var verimorReply = await _core.SendAsync(RawOperations.GetV2InboundMessages, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<GetV2InboundMessages200ResponseInner>>(verimorReply);
        }

        /// <summary>GET /v2/status</summary>
        public async Task<IReadOnlyList<GetSmsStatus200ResponseInner>> StatusAsync(
            long? id = null,
            string? dest = null,
            long? greaterThan = null,
            string? customId = null,
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            verimorCall.AddQuery("id", id);
            verimorCall.AddQuery("dest", dest);
            verimorCall.AddQuery("greater_than", greaterThan);
            verimorCall.AddQuery("custom_id", customId);
            var verimorReply = await _core.SendAsync(RawOperations.GetSmsStatus, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<GetSmsStatus200ResponseInner>>(verimorReply);
        }
    }
}
