// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.Sms.Generated.Model;

namespace BarisCemant.Verimor.Sms
{
    public sealed class SenderIdsService
    {
        private readonly ProductCore _core;

        internal SenderIdsService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>GET /v2/headers</summary>
        public async Task<IReadOnlyList<string>> ListSenderIdsAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.GetV2Headers, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<List<string>>(verimorReply);
        }
    }
}
