// GET /answer/{id} — Çağrıyı Cevaplama (GET)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class AnswerLegacyExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.Calls.AnswerLegacyAsync(
                id: "736eaf7e-4cc4-44ab-8dbe-16b18e9618b1"
            );
            Console.WriteLine(result);
        }
    }
}
