// POST /recording_url — Ses Kaydı için Geçici URL Oluşturma
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class CreateRecordingUrlExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.Records.CreateRecordingUrlAsync(
                callUuid: "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            );
            Console.WriteLine(result);
        }
    }
}
