// POST /fax_orders — Faks Gönderimi
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class CreateFaxOrderExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.Fax.CreateFaxOrderAsync(
                remoteStationId: "901234567891",
                filedata: "JVBERi0xLjQK"
            );
            Console.WriteLine(result);
        }
    }
}
