// POST /voicemail_recording_url — Telesekreter Ses Kaydı için Geçici URL Oluşturma
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class CreateVoicemailRecordingUrlExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.Records.CreateVoicemailRecordingUrlAsync(
                uuid: "12345678-1234-5678-4321-123456789012"
            );
            Console.WriteLine(result);
        }
    }
}
