// POST /fax_document_url — Faks Belgesi URL'si İsteme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class CreateFaxDocumentUrlExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.Fax.CreateFaxDocumentUrlAsync(
                callUuid: "e28e5d48-05d8-11e8-663a-fde60c59425c"
            );
            Console.WriteLine(result);
        }
    }
}
