// POST /ivr_campaigns.json — Otomatik Arama Kampanyası Oluşturma
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using BarisCemant.Verimor.Switch.Generated.Model;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class CreateIvrCampaignExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.IvrCampaigns.CreateIvrCampaignAsync(
                request: new CreateIvrCampaignRequest(
                    callType: "ivr",
                    name: "Memnuniyet anketi",
                    phoneList: new List<CreateIvrCampaignRequestPhoneListInner>
                    {
                        new CreateIvrCampaignRequestPhoneListInner(
                            phone: "05111111111",
                            phrase: "#429 12/05/2017 #430 102.45 #431",
                            lang: "tr-TR"),
                        new CreateIvrCampaignRequestPhoneListInner(
                            phone: "05111111112",
                            phrase: "#429 12/05/2017 #430 65.12 #431",
                            lang: "tr-TR"),
                    })
            );
            Console.WriteLine(result);
        }
    }
}
