// GET /fax_document/{id} — Faks Belgesi İndirme/Görüntüleme
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class DownloadFaxDocumentExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.Fax.DownloadFaxDocumentAsync(
                id: "123"
            );
            Console.WriteLine(result);
        }
    }
}
