// POST /originate — Çağrı Başlatma (POST)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using BarisCemant.Verimor.Switch.Generated.Model;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class OriginateExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.Calls.OriginateAsync(
                request: new OriginateCallPostRequest(
                    extension: "1001",
                    destination: "908505320000")
            );
            Console.WriteLine(result);
        }
    }
}
