// GET /originate — Çağrı Başlatma (GET)
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class OriginateLegacyExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.Calls.OriginateLegacyAsync(
                extension: "1001",
                destination: "908505320000"
            );
            Console.WriteLine(result);
        }
    }
}
