// GET /mute/{id} — Çağrıyı Sessize Alma / Sesli Yapma
// Generated by scripts/facades.py from the Verimor contract. Do not edit.

using BarisCemant.Verimor.Switch;
using System;
using System.Threading.Tasks;

namespace Examples.Operations.Switch
{
    public static class SetCallMuteExample
    {
        public static async Task RunAsync()
        {
            var client = new SwitchClient(new SwitchClientOptions
            {
                Key = Environment.GetEnvironmentVariable("VERIMOR_SWITCH_API_KEY") ?? string.Empty,
                BaseUri = new Uri(Environment.GetEnvironmentVariable("VERIMOR_BASE_URL") ?? "https://api.bulutsantralim.com"),
            });
            var result = await client.Calls.SetCallMuteAsync(
                id: "f3797dfc-a818-11e7-bf70-cb295b6663ce",
                state: "on"
            );
            Console.WriteLine(result);
        }
    }
}
