// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System.Collections.Generic;

namespace BarisCemant.Verimor.Sms
{
    internal static class RawOperations
    {
        public static readonly RawOperation DeleteV2BlacklistsId =
            new RawOperation(
                "delete_v2_blacklists_id",
                "DELETE",
                "/v2/blacklists/{id}",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                null);

        public static readonly RawOperation GetSmsStatus =
            new RawOperation(
                "getSmsStatus",
                "GET",
                "/v2/status",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                null);

        public static readonly RawOperation GetV2Balance =
            new RawOperation(
                "get_v2_balance",
                "GET",
                "/v2/balance",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                null);

        public static readonly RawOperation GetV2Blacklists =
            new RawOperation(
                "get_v2_blacklists",
                "GET",
                "/v2/blacklists",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                null);

        public static readonly RawOperation GetV2Headers =
            new RawOperation(
                "get_v2_headers",
                "GET",
                "/v2/headers",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                null);

        public static readonly RawOperation GetV2InboundMessages =
            new RawOperation(
                "get_v2_inbound_messages",
                "GET",
                "/v2/inbound_messages",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                null);

        public static readonly RawOperation GetV2IysCampaigns =
            new RawOperation(
                "get_v2_iys_campaigns",
                "GET",
                "/v2/iys/campaigns",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                null);

        public static readonly RawOperation GetV2IysCampaignsIdConsents =
            new RawOperation(
                "get_v2_iys_campaigns_id_consents",
                "GET",
                "/v2/iys/campaigns/{id}/consents",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                null);

        public static readonly RawOperation GetV2Send =
            new RawOperation(
                "get_v2_send",
                "GET",
                "/v2/send",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                "query");

        public static readonly RawOperation PostV2Blacklists =
            new RawOperation(
                "post_v2_blacklists",
                "POST",
                "/v2/blacklists",
                new Dictionary<string, string> { ["password"] = "query", ["username"] = "query" },
                null);

        public static readonly RawOperation PostV2CancelId =
            new RawOperation(
                "post_v2_cancel_id",
                "POST",
                "/v2/cancel/{id}",
                new Dictionary<string, string> { ["password"] = "body", ["username"] = "body" },
                null);

        public static readonly RawOperation PostV2IysConsentsJson =
            new RawOperation(
                "post_v2_iys_consents_json",
                "POST",
                "/v2/iys_consents.json",
                new Dictionary<string, string> { ["password"] = "body", ["username"] = "body" },
                "body");

        public static readonly RawOperation SendOtp =
            new RawOperation(
                "sendOtp",
                "POST",
                "/v2/otp",
                new Dictionary<string, string> { ["password"] = "body", ["username"] = "body" },
                null);

        public static readonly RawOperation SendSmsJson =
            new RawOperation(
                "sendSmsJson",
                "POST",
                "/v2/send.json",
                new Dictionary<string, string> { ["password"] = "body", ["username"] = "body" },
                "body");

        public static readonly IReadOnlyList<RawOperation> All = new RawOperation[]
        {
            DeleteV2BlacklistsId,
            GetSmsStatus,
            GetV2Balance,
            GetV2Blacklists,
            GetV2Headers,
            GetV2InboundMessages,
            GetV2IysCampaigns,
            GetV2IysCampaignsIdConsents,
            GetV2Send,
            PostV2Blacklists,
            PostV2CancelId,
            PostV2IysConsentsJson,
            SendOtp,
            SendSmsJson,
        };
    }
}
