// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using BarisCemant.Verimor.Http;

namespace BarisCemant.Verimor.Sms
{
    public sealed partial class SmsClient
    {
        public SmsClient(SmsClientOptions options)
        {
            if (options == null) throw new ArgumentNullException(nameof(options));
            var core = new ProductCore(
                new VerimorTransport(options, new Uri("https://sms.verimor.com.tr/")),
                options.ToCredentials(),
                options.DefaultSender);
            Raw = new RawClient(core, RawOperations.All);
            Balances = new BalancesService(core);
            Blacklist = new BlacklistService(core);
            Campaigns = new CampaignsService(core);
            Iys = new IysService(core);
            Reports = new ReportsService(core);
            SenderIds = new SenderIdsService(core);
        }

        public RawClient Raw { get; }

        public BalancesService Balances { get; }

        public BlacklistService Blacklist { get; }

        public CampaignsService Campaigns { get; }

        public IysService Iys { get; }

        public ReportsService Reports { get; }

        public SenderIdsService SenderIds { get; }
    }
}
