// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.WhatsApp.Generated.Model;

namespace BarisCemant.Verimor.WhatsApp
{
    public sealed class HealthService
    {
        private readonly ProductCore _core;

        internal HealthService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>GET /health</summary>
        public async Task<JsonElement> HealthAsync(
            CancellationToken cancellationToken = default)
        {
            var verimorCall = new CallParts();
            var verimorReply = await _core.SendAsync(RawOperations.HealthHealthGet, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Element(verimorReply);
        }
    }
}
