// <auto-generated/> Generated by the Verimor SDK generator. Do not edit.
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using BarisCemant.Verimor.Http;
using BarisCemant.Verimor.WhatsApp.Generated.Model;

namespace BarisCemant.Verimor.WhatsApp
{
    public sealed class MessagesService
    {
        private readonly ProductCore _core;

        internal MessagesService(ProductCore core)
        {
            _core = core;
        }

        /// <summary>POST /v1/messages/otp</summary>
        public async Task<MessageResponse> SendOtpAsync(
            TemplateMessageRequest request,
            CancellationToken cancellationToken = default)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            var verimorCall = new CallParts();
            verimorCall.JsonBody = VerimorJson.Serialize(request);
            var verimorReply = await _core.SendAsync(RawOperations.SendOtpV1MessagesOtpPost, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<MessageResponse>(verimorReply);
        }

        /// <summary>POST /v1/messages/utility</summary>
        public async Task<MessageResponse> SendUtilityAsync(
            TemplateMessageRequest request,
            CancellationToken cancellationToken = default)
        {
            if (request == null) throw new ArgumentNullException(nameof(request));
            var verimorCall = new CallParts();
            verimorCall.JsonBody = VerimorJson.Serialize(request);
            var verimorReply = await _core.SendAsync(RawOperations.SendUtilityV1MessagesUtilityPost, verimorCall, cancellationToken).ConfigureAwait(false);
            return ResponseReader.Json<MessageResponse>(verimorReply);
        }
    }
}
